{{- if and .Values.notifier.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- with .Values.notifier.podMonitor.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: http
      interval: {{ .Values.notifier.podMonitor.scrapeInterval | default "60s"}}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
{{- end }}
