
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm.serviceAccountName" . }}-role
rules:
  - apiGroups: ["spirit-dev.net"]
    resources: ["upsstatuses"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.serviceAccountName" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.serviceAccountName" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "helm.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
