{{- if and .Values.notifier.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- with .Values.notifier.serviceMonitor.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.notifier.serviceMonitor.scrapeInterval }}
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
{{- end }}
